# Generated by Django 2.2.5 on 2023-09-18 15:00

from django.db import migrations
from datetime import date, time, datetime, timedelta

def daterange(start_date, end_date):
     for n in range(0, int((end_date - start_date).days) + 1, 7):
         yield start_date + timedelta(n)

def initialize_week_data(apps, schema_editor):
	week_model = apps.get_model('dashboard','Week')

	week_model.objects.create(
		week_num = 1,
		start_date = date(1998, 1, 21),
		end_date = date(1998, 1, 25))

	start_dt = date(1998, 1, 26)
	end_dt = date(2077, 12, 31)
	week_num = 2

	for dt in daterange(start_dt, end_dt):
		week_model.objects.create(
			week_num = week_num,
			start_date = dt,
			end_date = dt + timedelta(6))
		week_num += 1

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
    	migrations.RunPython(initialize_week_data),
    ]
