# Generated by Django 2.2.5 on 2023-09-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20230919_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='color',
            new_name='color1',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='color',
            new_name='color1',
        ),
        migrations.AddField(
            model_name='experience',
            name='color2',
            field=models.CharField(default='#ffffff', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='color2',
            field=models.CharField(default='#ffffff', max_length=7),
            preserve_default=False,
        ),
    ]
