# Generated by Django 2.2.5 on 2024-06-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20240615_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='location',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.LocationInstance'),
        ),
    ]
