# Generated by Django 2.2.5 on 2024-06-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20240615_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experienceinstance',
            name='experience',
        ),
        migrations.AddField(
            model_name='experienceinstance',
            name='base_color',
            field=models.CharField(default='#f4f4f4', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experienceinstance',
            name='highlight_color',
            field=models.CharField(default='#999999', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experienceinstance',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
