# Generated by Django 2.2.5 on 2024-06-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20240615_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceinstance',
            name='subname',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
