# Generated by Django 2.2.5 on 2024-06-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_experienceinstance_subname'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationinstance',
            name='sublocation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='experienceinstance',
            name='experience_type',
            field=models.CharField(choices=[('w', 'Work'), ('e', 'Education'), ('o', 'Other')], default='o', max_length=1),
        ),
        migrations.AlterField(
            model_name='locationinstance',
            name='location_type',
            field=models.CharField(choices=[('t', 'Travel'), ('l', 'Living'), ('o', 'Other')], default='o', max_length=1),
        ),
    ]
