# Generated by Django 2.2.5 on 2024-06-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20240616_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienceinstance',
            name='experience_type',
            field=models.CharField(choices=[('a', 'Work'), ('b', 'Education'), ('c', 'Other')], default='c', max_length=1),
        ),
        migrations.AlterField(
            model_name='locationinstance',
            name='location_type',
            field=models.CharField(choices=[('a', 'Travel'), ('b', 'Hybrid'), ('c', 'Living'), ('d', 'Other')], default='d', max_length=1),
        ),
    ]
