# Generated by Django 2.2.5 on 2024-06-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20240617_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienceinstance',
            name='subname',
            field=models.CharField(max_length=200),
        ),
    ]
