# Generated by Django 3.1.2 on 2023-09-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(max_length=1000)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('experience_type', models.CharField(blank=True, choices=[('e', 'Education'), ('w', 'Work'), ('o', 'Other')], default='o', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(max_length=1000)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_num', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('log', models.TextField(max_length=1000)),
                ('experience', models.ManyToManyField(null=True, to='dashboard.Experience')),
                ('location', models.ManyToManyField(null=True, to='dashboard.Location')),
            ],
        ),
    ]
