# Generated by Django 3.1.2 on 2023-09-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='experience',
            field=models.ManyToManyField(to='dashboard.Experience'),
        ),
        migrations.AlterField(
            model_name='week',
            name='location',
            field=models.ManyToManyField(to='dashboard.Location'),
        ),
    ]
