# Generated by Django 2.2.5 on 2023-09-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20230904_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='experience',
            field=models.ManyToManyField(blank=True, to='dashboard.Experience'),
        ),
        migrations.AlterField(
            model_name='week',
            name='location',
            field=models.ManyToManyField(blank=True, to='dashboard.Location'),
        ),
        migrations.AlterField(
            model_name='week',
            name='log',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
