# Generated by Django 2.2.5 on 2023-09-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20230918_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='experience_type',
        ),
        migrations.AddField(
            model_name='experienceinstance',
            name='experience_type',
            field=models.CharField(blank=True, choices=[('e', 'Education'), ('w', 'Work'), ('o', 'Other')], default='o', max_length=1),
        ),
        migrations.AddField(
            model_name='experienceinstance',
            name='notes',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='locationinstance',
            name='location_type',
            field=models.CharField(blank=True, choices=[('l', 'Living'), ('h', 'Hybrid'), ('t', 'Travel'), ('o', 'Other')], default='o', max_length=1),
        ),
    ]
