# Generated by Django 2.2.5 on 2023-09-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20230919_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienceinstance',
            name='experience_type',
            field=models.CharField(choices=[('e', 'Education'), ('w', 'Work'), ('o', 'Other')], default='o', max_length=1),
        ),
        migrations.AlterField(
            model_name='locationinstance',
            name='location_type',
            field=models.CharField(choices=[('l', 'Living'), ('h', 'Hybrid'), ('t', 'Travel'), ('o', 'Other')], default='o', max_length=1),
        ),
    ]
