# Generated by Django 2.2.5 on 2023-10-28 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20230925_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='color1',
            new_name='base_color',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='color2',
            new_name='highlight_color',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='color1',
            new_name='base_color',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='color2',
            new_name='highlight_color',
        ),
        migrations.AlterField(
            model_name='locationinstance',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.Location'),
        ),
        migrations.AlterField(
            model_name='week',
            name='location',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.LocationInstance'),
        ),
    ]
